name: Model Training
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  model-training:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
